# General Configuration
run_name: "uncertainty_run"
task: "classification"  # Options: "classification", "regression"
model_type: "mlp"       # Options: "linear", "mlp"
output_file: "probe.pth"


files:
  # - "data/Qwen3-1.7B/mmlu/nn-short-100.pt"
  # - "data/Qwen3-1.7B/mmlu/nn-short-100-high-entropy.pt"
  # - "data/Qwen3-1.7B/mmlu/nn-long-4.pt"
  - "half-normal.pt"
  - "half-high.pt"

# List of file paths whose samples should be EXCLUDED from the validation split
exclude_val:
  # - "data/Qwen3-1.7B/mmlu/nn-short-100-high-entropy.pt"
  # - "half.pt"
  - "half-high.pt"


# Activation field to use 
activation_field: "cut_cot_activations"  # Options: "activations", "cut_cot_activations"

# Dataset preprocessing
preprocessing:
  percentage_dataset: 1  # Use fraction of dataset (0.0-1.0)
  normalize_inputs: true  # Normalize input features to zero mean, unit variance
  remove_zeroes: false
  zero_tolerance: 0.01

# Training Hyperparameters
training:
  epochs: 128
  batch_size: 4096
  learning_rate: 5.0e-5  
  weight_decay: 1.0e-1
  val_split: 0.15
  patience: 15  # Early stopping patience
  scheduler:
    enabled: true
    factor: 0.5
    patience: 5

# Task-Specific Settings
task_specific:
  classification:
    label_type: "entropy"  # Options: "hard", "soft", "entropy", "variance"
    soft_label_threshold: 0.01  # Threshold for binarizing soft/entropy labels
    
    # Evaluation
    val_threshold: "auto"  # Threshold for validation predictions. Use "auto" for automatic optimization.
    
    # Data balancing
    balance_data: true
    balance_strategy: 'smote'  # Options: 'undersample', 'oversample', 'smote'
    smote_k_neighbors: 5
    
  regression:
    # Label configuration
    label_field: "entropy"  # Field name in data
    use_transformation: false  # Apply logit transformation

# Model-Specific Settings
model_specific:
  mlp:
    hidden_dims: [64]  # Hidden layer dimensions
    dropout_p: 0.6          # Dropout probability 